<Project>
	<PropertyGroup>
		<Product>MPV.NET Media Player</Product>
		<AssemblyTitle>MPV.NET Media Player</AssemblyTitle>
		<Company>Wanderson Estanislau de Souza Rodrigues</Company>
		<Authors>Wanderson Estanislau de Souza Rodrigues</Authors>
		<Copyright>Copyright (C) Wanderson Estanislau de Souza Rodrigues</Copyright>
		<Description>MPV.NET Media Player for Windows, based on mpv.net and mpv/libmpv.</Description>
		<PackageProjectUrl>https://github.com/WandersondeSouza/mpv.net</PackageProjectUrl>
		<RepositoryUrl>https://github.com/WandersondeSouza/mpv.net</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<LangVersion>12.0</LangVersion>
		<Nullable>enable</Nullable>
		<Platforms>x64</Platforms>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
		<EnableFileLogging Condition="'$(EnableFileLogging)' == ''">false</EnableFileLogging>
		<DefineConstants Condition="'$(EnableFileLogging)' == 'true'">$(DefineConstants);ENABLE_FILE_LOGGING</DefineConstants>
	</PropertyGroup>
</Project>
