<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="NGettext" Version="0.6.7" />
    <PackageVersion Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" />
  </ItemGroup>
</Project>
